#!/usr/bin/env python

import os
import codecs

PY = 'src/runner.py'
MONO = '1ftn'

py_code = open(PY).read()
py_code = py_code.replace('{{{HTML_FILE}}}', open('src/index.html').read())
py_code = py_code.replace('{{{STYLE}}}', open('src/_style.css').read())
py_code = py_code.replace('{{{JS_CODE}}}', open('src/_code.js').read())
py_code = py_code.replace('{{{SVG_FILE}}}', codecs.encode(open('src/icons.svg').read().encode('utf-8'), 'base64').decode().replace('\n', ''))
open(MONO, 'w').write(py_code)
os.chmod(MONO, 0o777)
