#!/usr/bin/env python

import os

PY = 'src/runner.py'
MONO = '1ftn'

py_code = open(PY).read()
py_code = py_code.replace('{{{HTML_FILE}}}', open('src/index.html').read())
py_code = py_code.replace('{{{STYLE}}}', open('src/style.css').read())
py_code = py_code.replace('{{{JS_CODE}}}', open('src/code.js').read())
open(MONO, 'w').write(py_code)
os.chmod(MONO, 0o777)
